
import edu.uniciencia.directorio.daos.PersonaDAO;
import edu.uniciencia.directorio.datos.Persona;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

public class FrmPersona extends javax.swing.JInternalFrame {

    ModeloTablaPersona modelo = null;
    PersonaDAO dao = null;
    Map<String, Persona> db = new HashMap<>();

    public FrmPersona() {
        initComponents();
        dao = new PersonaDAO();
        modelo = new ModeloTablaPersona();

        jTable1.setModel(modelo);
        modelo.fireTableDataChanged();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNumeroDoc = new javax.swing.JLabel();
        jTxtNumero = new javax.swing.JTextField();
        jLabelNombres = new javax.swing.JLabel();
        jTxtNombres = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTxtApellidos = new javax.swing.JTextField();
        jLabelDpto = new javax.swing.JLabel();
        jComboBoxDpto = new javax.swing.JComboBox<>();
        jLabelMunic = new javax.swing.JLabel();
        jComboBoxMunic = new javax.swing.JComboBox<>();
        jLabelFecha = new javax.swing.JLabel();
        jTxtFecha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBtnBuscar = new javax.swing.JButton();
        jBtnAgregar = new javax.swing.JButton();
        jBtnActualizar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnLimpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(575, 375));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        jLabelNumeroDoc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNumeroDoc.setText("Id");
        jPanel1.add(jLabelNumeroDoc);
        jPanel1.add(jTxtNumero);

        jLabelNombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNombres.setText("Nombres");
        jPanel1.add(jLabelNombres);
        jPanel1.add(jTxtNombres);

        jLabelApellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelApellidos.setText("Apellidos");
        jPanel1.add(jLabelApellidos);

        jTxtApellidos.setToolTipText("");
        jPanel1.add(jTxtApellidos);

        jLabelDpto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDpto.setText("Dpto");
        jPanel1.add(jLabelDpto);

        jComboBoxDpto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santander" }));
        jPanel1.add(jComboBoxDpto);

        jLabelMunic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMunic.setText("Municipio");
        jPanel1.add(jLabelMunic);

        jComboBoxMunic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bucaramanga" }));
        jPanel1.add(jComboBoxMunic);

        jLabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelFecha.setText("Fecha");
        jPanel1.add(jLabelFecha);

        jTxtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtFecha);

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBuscarMouseClicked(evt);
            }
        });
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAgregarMouseClicked(evt);
            }
        });
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jBtnActualizar.setText("Actualizar");
        jBtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualizarActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jBtnLimpiar.setText("Limpiar");
        jBtnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLimpiarMouseClicked(evt);
            }
        });

        jButton1.setText("Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnBuscar)
                .addGap(18, 18, 18)
                .addComponent(jBtnActualizar)
                .addGap(18, 18, 18)
                .addComponent(jBtnAgregar)
                .addGap(18, 18, 18)
                .addComponent(jBtnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jBtnLimpiar))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnBuscar)
                    .addComponent(jBtnActualizar)
                    .addComponent(jBtnAgregar)
                    .addComponent(jBtnEliminar)
                    .addComponent(jBtnLimpiar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Id"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jBtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarActionPerformed
        Persona p = dao.buscarPersona(jTxtNumero.getText());
        if (p == null) {
            JOptionPane.showMessageDialog(this, "No encontrado");
            return;
        }
        copiarDatos(p, true);
        dao.actualizarPersona(p);
        limpiar();
        cargarTabla();
    }//GEN-LAST:event_jBtnActualizarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        dao.eliminarPersona(jTxtNumero.getText());
        limpiar();
        cargarTabla();
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jBtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarMouseClicked

    }//GEN-LAST:event_jBtnAgregarMouseClicked

    private void jBtnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLimpiarMouseClicked
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jBtnLimpiarMouseClicked

    private void jBtnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBuscarMouseClicked

    }//GEN-LAST:event_jBtnBuscarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed

        Persona p = dao.buscarPersona(jTxtNumero.getText());
        if (p != null) {
            copiarDatos(p, false);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        Persona p = new Persona();
        copiarDatos(p, true);
        dao.agregarPersona(p);
        JOptionPane.showMessageDialog(this, "Se ha guardado exitosamente.");
        limpiar();
        cargarTabla();
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jTxtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualizar;
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxDpto;
    private javax.swing.JComboBox<String> jComboBoxMunic;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDpto;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelMunic;
    private javax.swing.JLabel jLabelNombres;
    private javax.swing.JLabel jLabelNumeroDoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtApellidos;
    private javax.swing.JTextField jTxtFecha;
    private javax.swing.JTextField jTxtNombres;
    private javax.swing.JTextField jTxtNumero;
    // End of variables declaration//GEN-END:variables

    public void copiarDatos(Persona p, boolean x) {
        if (x) {
            p.setId(jTxtNumero.getText());
            p.setNombres(jTxtNombres.getText());
            p.setApellidos(jTxtApellidos.getText());
            p.setMunic(jComboBoxMunic.getSelectedItem() + "");
            p.setDpto(jComboBoxDpto.getSelectedItem() + "");
            p.setFecha(jTxtFecha.getText());
        } else {
            jTxtNombres.setText(p.getNombres());
            jTxtApellidos.setText(p.getApellidos());
            jComboBoxMunic.setSelectedItem(p.getMunic());
            jComboBoxDpto.setSelectedItem(p.getDpto());
            jTxtFecha.setText(p.getFecha());
        }
    }

    public void limpiar() {
        jTxtNombres.setText("");
        jTxtApellidos.setText("");
        jTxtNumero.setText("");
        jComboBoxMunic.setSelectedItem("");
        jComboBoxDpto.setSelectedItem("");
        jTxtFecha.setText("");
    }

    public void cargarTabla() {
        List<Persona> lista = dao.getListaPersonas();
        modelo.setLista(lista);
        modelo.fireTableDataChanged();
    }
}
